<?php

namespace app\migrations;

use app\core\migration;

class MigrateCreatTableComments extends Migration
{
    public function creat()
    {
        $params = 'CREATE TABLE IF NOT EXISTS `comments` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `text` varchar(255) NOT NULL,
  `parent` int(11) NOT NULL,
  `user_id` varchar(20)  NOT NULL,
  `create_at` datetime NOT NULL,
   PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
';
        parent::creat($params); // TODO: Change the autogenerated stub
    }
}