<?php

namespace app\migrations;

use app\core\migration;

class MigrateCreatTableUsers extends Migration
{
    public function creat()
    {
        $params = 'CREATE TABLE IF NOT EXISTS `users` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `create_at` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;';
        parent::creat($params); // TODO: Change the autogenerated stub
    }
}