<?php

namespace app\migrations;

use app\core\migration;

class MigrateCreatTableUsers extends Migration
{
    public function creat()
    {
        $params = 'CREATE TABLE IF NOT EXISTS `users` (
  `id` varchar(20) NOT NULL,
  `name` varchar(255) NOT NULL,
  `email` varchar(255) NOT NULL,
  `token` varchar(255) NOT NULL,
  `create_at` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
';
        parent::creat($params); // TODO: Change the autogenerated stub
    }
}