<?php

namespace app\migrations;

use app\core\migration;

class MigrateCreatTableComments extends Migration
{
    public function creat()
    {
        $params = 'CREATE TABLE IF NOT EXISTS `comments` (
  `id` int(11) DEFAULT NULL,
  `text` varchar(255) NOT NULL,
  `parent` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `creat_at` date NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
';
        parent::creat($params); // TODO: Change the autogenerated stub
    }
}