<?php

namespace app\migrations;

use app\core\migration;

class MigrateCreatTableComments extends Migration
{
    public function creat()
    {
        $params = 'CREATE TABLE IF NOT EXISTS `comments` (
  `id` int(11)  AUTO_INCREMENT,
  `text` varchar(255) NOT NULL,
  `parent` int(11) NOT NULL,
  `user_id` varchar(20)  NOT NULL,
  `create_at` datetime NOT NULL,
   PRIMARY KEY (`id`),
   KEY `FK_comments` (`parent`),
   CONSTRAINT `FK_comments` FOREIGN KEY (`parent`) REFERENCES `comments` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
  ) ENGINE=InnoDB DEFAULT CHARSET=utf8';
        parent::creatTable($params); // TODO: Change the autogenerated stub
    }
}